version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql

  javavulny:
    build: .
    image: 478468688580.dkr.ecr.us-east-1.amazonaws.com/hawkdog
    container_name: javavulny
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db
