# This is a basic workflow to help you get started with Actions

name: Push to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the PROD branch
  push:
    branches: [ PROD ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Make sure all the AWS bits are good!
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Amazon ECR Action 
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      # Check out the Code after the AWS creds are validated
      - uses: actions/checkout@v2
      
      # Build and Push the HawkDog 
      - name: Build, Tag, and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: hawkdog
          IMAGE_TAG: PROD
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


